### ISSUE TITLE
Package names don't match directory names

### ISSUE THREAD

**Issue by boris-kolpackov** [build2-packaging/nanoflann#1]
I've noticed that the package names (`nanoflann-tests` and `nanoflann-examples`) don't match their top-level directory names within the repository (`tests` and  `examples`). This is non-canonical and while it seems to work, is not guaranteed to (and may not in certain contexts).

**Comment by lyrahgames** [comment]
I have not been aware of the fact that it is a non-canonical project structure.
Up to now, I thought that it does not matter whether package name and directory name are the same.

I have addressed this issue in the last commit.

**Comment by lyrahgames** [comment]
[Here](https://ci.cppget.org/@cc8cea78-221c-4700-ac89-d6b3eb711b6d) is the new CI build.
The are the same issues as before with the `freebsd_13-clang_14.0-static_O3` and `linux_debian_11-emcc_3.1.6` builds.

**Comment by boris-kolpackov** [comment]
Yes, looks much better, thanks!
