### ISSUE TITLE
Drop `install` module instead of `./: install = false`

### ISSUE THREAD

**Issue by boris-kolpackov** [build2-packaging/nanoflann#2]
I've noticed that in both tests and examples packages there is the following line in the root `buildfile`:

```
./: install = false
```

The more direct and efficient way to achieve the same result would be to drop the `install` module loading form `bootstrap.build`.

**Comment by lyrahgames** [comment]
I have already tried to drop the install module for tests packages in other projects.
But this made it impossible to install the library from the root directory of the repository.

```
$ b install
error: no rule to update (for install) ../nanoflann-gcc/fsdir{nanoflann-examples/}
  info: target ../nanoflann-gcc/fsdir{nanoflann-examples/} is not declared in any buildfile
  info: re-run with --verbose=4 for more information
  info: while applying rule build.alias to update (for install) ../nanoflann-gcc/dir{nanoflann-examples/}
  info: while applying rule install.alias to update (for install) dir{./}
info: failed to update (for install) dir{./}
```
Instead, I have to be inside the package that supports `install` or need to call something like `b install: nanoflann/`.
Of course, this is no big issue.
Still, for convenience, I enabled the `install` module and used `./: install = false` to be able to run `b install` from the root directory without issues.

The last commit should address this issue.

**Comment by lyrahgames** [comment]
[Here](https://ci.cppget.org/@cc8cea78-221c-4700-ac89-d6b3eb711b6d) is the new CI build.
The are the same issues as before with the `freebsd_13-clang_14.0-static_O3` and `linux_debian_11-emcc_3.1.6` builds.

**Comment by boris-kolpackov** [comment]
> But this made it impossible to install the library from the root directory of the repository.

Probably the more correct way to handle this would be to fix the glue `buildfile` not to pull those packages for `install`. Something along these lines:

```
import pkgs = {*/ -upstream/ -*-tests/ -*-examples/}
import tests = {-*-tests/ -*-examples/}

./: $pkgs
./: $tests: install = false
```

I haven't tested this, but I think it should do the right thing.

**Comment by lyrahgames** [comment]
Thanks for the solution. It works!

**Comment by lyrahgames** [comment]
> ```
> import pkgs = {*/ -upstream/ -*-tests/ -*-examples/}
> import tests = {-*-tests/ -*-examples/}
> 
> ./: $pkgs
> ./: $tests: install = false
> ```

As a note: I think there is a typo in this code.
The correct variant should be as follows without the prepended `-` for the tests packages:

```
import pkgs = {*/ -*-tests/ -*-examples/ -upstream/}
import tests = {*-tests/ *-examples/}

./: $pkgs
./: $tests: install = false
```
[Here](https://ci.cppget.org/@f4e6deb2-4bb7-4928-b1f5-4cf115cd85e3) is an updated CI run. I consider this issue to be closed and will submit a new revision.

**Comment by boris-kolpackov** [comment]
> The correct variant should be as follows without the prepended `-` for the tests packages

Yes, that was a copy-paste mistake, thanks!
